sef_roboter:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # JointTrajectoryController ----------------------------------
  joints_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}
      joint_2: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}
      joint_3: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}
      joint_4: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}
      joint_5: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}
      joint_6: {p: 3.5, i: 0, d: 0, i_clamp_min: 0, i_clamp_max: 0}